# Numpy2

In [ ]:
import numpy as np
arravali = np.array(np.random.randint(10,45,(8,2)))
print(f"The defined array is \n{arravali}")
print(f" \n The shape of the array is {arravali.shape}")

The defined array is 
[[39 16]
 [21 16]
 [32 44]
 [31 20]
 [32 24]
 [33 34]
 [37 24]
 [23 21]]
 
 The shape of the array is (8, 2)


In [ ]:
nilgiri = np.transpose(arravali)
print(f" This transpose of the array is \n{nilgiri}")
print(f" \n The shape of the array is {nilgiri.shape}")

 This transpose of the array is 
[[39 21 32 31 32 33 37 23]
 [16 16 44 20 24 34 24 21]]
 
 The shape of the array is (2, 8)


In [ ]:
random_3d_array = np.array(np.random.randint(10,45,(3,2,4)))
print(f"The defined array is \n{random_3d_array}")
print(f" \n The shape of the array is {random_3d_array.shape}")

The defined array is 
[[[22 35 22 39]
  [38 36 13 42]]

 [[31 42 31 14]
  [30 37 21 19]]

 [[40 41 14 32]
  [23 40 23 44]]]
 
 The shape of the array is (3, 2, 4)


In [ ]:
transpose_3d_array = np.transpose(random_3d_array)
print(f" This transpose of the array is \n{transpose_3d_array}")
print(f" \n The shape of the array is {transpose_3d_array.shape}")

 This transpose of the array is 
[[[22 31 40]
  [38 30 23]]

 [[35 42 41]
  [36 37 40]]

 [[22 31 14]
  [13 21 23]]

 [[39 14 32]
  [42 19 44]]]
 
 The shape of the array is (4, 2, 3)


In [ ]:
random_cohort = np.array(np.random.randint(10,45,(3,8)))
print(f"The defined array is \n{random_cohort}")
print(f" \n The shape of the array is {random_cohort.shape}")

The defined array is 
[[21 22 43 36 28 12 18 23]
 [24 42 39 33 22 36 19 24]
 [20 40 30 16 39 22 25 31]]
 
 The shape of the array is (3, 8)


In [ ]:
new_shape = (2,6,2)
reshaped_random_cohort = np.reshape(random_cohort,new_shape)
print(f"This reshaped array is \n{reshaped_random_cohort}")
print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

This reshaped array is 
[[[21 22]
  [43 36]
  [28 12]
  [18 23]
  [24 42]
  [39 33]]

 [[22 36]
  [19 24]
  [20 40]
  [30 16]
  [39 22]
  [25 31]]]
 
 The shape of the array is (2, 6, 2)


In [ ]:
new_shape = (2,-1,6)
reshaped_random_cohort = np.reshape(random_cohort,new_shape)
print(f"This reshaped array is \n{reshaped_random_cohort}")
print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

This reshaped array is 
[[[21 22 43 36 28 12]
  [18 23 24 42 39 33]]

 [[22 36 19 24 20 40]
  [30 16 39 22 25 31]]]
 
 The shape of the array is (2, 2, 6)


In [ ]:
random_3D_cohort = np.array(np.random.randint(10,45,(3,6,2)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[21 12]
  [16 27]
  [21 35]
  [26 12]
  [37 39]
  [28 23]]

 [[42 29]
  [32 42]
  [15 21]
  [17 37]
  [20 14]
  [35 35]]

 [[25 11]
  [22 38]
  [38 21]
  [23 12]
  [32 44]
  [25 32]]]
 
 The shape of the array is (3, 6, 2)


In [ ]:
new_shape = (2,1,6)
resize_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resize_random_3D_cohort}")
print(f" \n The shape of the array is {resize_random_3D_cohort.shape}")

This resized array is 
[[[21 12 16 27 21 35]]

 [[26 12 37 39 28 23]]]
 
 The shape of the array is (2, 1, 6)


In [ ]:
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[37 10 11 15 24 23]
  [27 19 25 31 17 31]
  [44 40 28 29 21 11]
  [38 13 44 42 14 28]]

 [[20 40 39 43 37 24]
  [29 10 43 38 42 24]
  [22 11 28 20 28 28]
  [35 32 33 11 34 23]]]
 
 The shape of the array is (2, 4, 6)


In [ ]:
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resize_random_3D_cohort}")
print(f" \n The shape of the array is {resize_random_3D_cohort.shape}")

This resized array is 
[[[21 12 16 27 21 35]]

 [[26 12 37 39 28 23]]]
 
 The shape of the array is (2, 1, 6)


In [ ]:
import numpy as np
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[25 11 34 23 44 35]
  [11 27 22 18 35 24]
  [25 11 11 29 18 20]
  [35 17 25 21 36 37]]

 [[29 31 32 26 28 15]
  [41 14 39 31 43 12]
  [27 13 15 30 38 16]
  [34 18 43 38 44 23]]]
 
 The shape of the array is (2, 4, 6)


In [ ]:
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resized_random_3D_cohort}")
print(f" \n The shape of the array is {resized_random_3D_cohort.shape}")

This resized array is 
[[[25 11 34 23 44 35]
  [11 27 22 18 35 24]
  [25 11 11 29 18 20]]

 [[35 17 25 21 36 37]
  [29 31 32 26 28 15]
  [41 14 39 31 43 12]]]
 
 The shape of the array is (2, 3, 6)


In [ ]:
import numpy as np
a = np.random.randint(10,20,(2,3,4))   #Axis 0-2 ; Axis 1-3 ; Axis 2-4
print(a)
print(a.shape)

[[[15 14 17 19]
  [13 18 19 10]
  [15 17 12 17]]

 [[10 15 12 14]
  [17 14 12 17]
  [19 10 13 10]]]
(2, 3, 4)


In [ ]:
#Insert along axis = 0
np.insert(a,1,100,axis=0)

array([[[ 15,  14,  17,  19],
        [ 13,  18,  19,  10],
        [ 15,  17,  12,  17]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 10,  15,  12,  14],
        [ 17,  14,  12,  17],
        [ 19,  10,  13,  10]]])

In [ ]:
#Insert along axis = 2
np.insert(a,0,200,axis=2)

array([[[200,  15,  14,  17,  19],
        [200,  13,  18,  19,  10],
        [200,  15,  17,  12,  17]],

       [[200,  10,  15,  12,  14],
        [200,  17,  14,  12,  17],
        [200,  19,  10,  13,  10]]])

In [ ]:
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[4 5 5]
  [2 3 4]
  [3 4 2]]

 [[5 5 5]
  [2 3 3]
  [4 3 3]]]
(2, 3, 3)


In [ ]:
np.append(a,50)

array([ 4,  5,  5,  2,  3,  4,  3,  4,  2,  5,  5,  5,  2,  3,  3,  4,  3,
        3, 50])

In [ ]:
b = np.random.randint(2,6,(2,1,3))
print(b)

[[[3 5 4]]

 [[5 3 5]]]


In [ ]:
print(a)
print(a.shape)

[[[4 5 5]
  [2 3 4]
  [3 4 2]]

 [[5 5 5]
  [2 3 3]
  [4 3 3]]]
(2, 3, 3)


In [ ]:
np.append(a,b,axis=1)

array([[[4, 5, 5],
        [2, 3, 4],
        [3, 4, 2],
        [3, 5, 4]],

       [[5, 5, 5],
        [2, 3, 3],
        [4, 3, 3],
        [5, 3, 5]]])

In [3]:
import numpy as np
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[5 4 4]
  [3 5 2]
  [2 2 2]]

 [[4 5 4]
  [4 5 4]
  [4 5 3]]]
(2, 3, 3)


In [4]:
np.delete(a,(0),axis = 0)

array([[[4, 5, 4],
        [4, 5, 4],
        [4, 5, 3]]])

In [5]:
np.delete(a,(0,2),axis = 1)

array([[[3, 5, 2]],

       [[4, 5, 4]]])

In [6]:
a

array([[[5, 4, 4],
        [3, 5, 2],
        [2, 2, 2]],

       [[4, 5, 4],
        [4, 5, 4],
        [4, 5, 3]]])

In [7]:
np.delete(a,(0,1),axis = 2)

array([[[4],
        [2],
        [2]],

       [[4],
        [4],
        [3]]])

In [8]:
a = np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)

[[[18 12  5]
  [10 18  8]
  [ 5 13  4]]

 [[16 11 14]
  [13 17  4]
  [14 11  7]]]
(2, 3, 3)


In [9]:
np.unique(a)

array([ 4,  5,  7,  8, 10, 11, 12, 13, 14, 16, 17, 18])

In [10]:
np.unique(a,return_counts=True)

(array([ 4,  5,  7,  8, 10, 11, 12, 13, 14, 16, 17, 18]),
 array([2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2]))

In [12]:
np.unique(a,return_counts=True,return_index=True)

(array([ 4,  5,  7,  8, 10, 11, 12, 13, 14, 16, 17, 18]),
 array([ 8,  2, 17,  5,  3, 10,  1,  7, 11,  9, 13,  0]),
 array([2, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2]))

In [13]:
a = [1,2,3]
b= a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [14]:
a = [1,2,3]
b= a.copy()
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


In [17]:
a = np.array([2,34,12])
b = a
b[0] = -999
print(b)
print(a)

[-999   34   12]
[-999   34   12]


In [18]:
a = np.array([2,34,12])
b = a.copy()
b[0] = -999
print(b)
print(a)

[-999   34   12]
[ 2 34 12]


In [20]:
np.arange(3) + 5

array([5, 6, 7])

In [21]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [23]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [24]:
np.arange(3).reshape((3,1)) + np.arange(4)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [25]:
np.arange(2)

array([0, 1])

In [26]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(1,10,(2,2))
print(b)

[[3 4 4 2]
 [2 5 3 2]]
[[1 8]
 [8 1]]


In [27]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [28]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(0,5,(2,4))
print(b)

[[3 2 3 2]
 [2 5 4 3]]
[[1 3 2 2]
 [1 3 4 0]]


In [29]:
np.multiply(a,b)

array([[ 3,  6,  6,  4],
       [ 2, 15, 16,  0]])

In [30]:
np.divide(a,b)

<ipython-input-30-c364992e28ce>:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([[3.        , 0.66666667, 1.5       , 1.        ],
       [2.        , 1.66666667, 1.        ,        inf]])

In [53]:
a=np.random.randint(5,9,(2,4))
print(a)

[[5 7 6 5]
 [6 8 6 5]]


In [54]:
print(np.sum(a))
print(np.sum(a,axis = 0))
print(np.sum(a,axis = 1))

48
[11 15 12 10]
[23 25]


In [62]:
print(np.min(a))
print(np.min(a,axis=1)) #Across Column
a =np.random.randint(0,20,(3,3))
print(a)

0
[10  8  0]
[[ 5  9 12]
 [ 6  1 16]
 [ 6 19 16]]


In [64]:
print(np.sort(a,axis=0)) # Ascending

[[ 5  1 12]
 [ 6  9 16]
 [ 6 19 16]]


In [65]:
print(np.sort(a,axis=1))

[[ 5  9 12]
 [ 1  6 16]
 [ 6 16 19]]


In [66]:
print(-np.sort(-a,axis=1)) #Descending

[[12  9  5]
 [16  6  1]
 [19 16  6]]


In [69]:
sum(np.arange(3)*np.arange(3).transpose())

5